### ISSUE TITLE
BUG: Unable to create domain error 403,0

### ISSUE THREAD

**Issue by KillerVan** [face-hh/webx#156] opened 2024-06-04 08:01 UTC
I downloaded the windows latest release and tried to create a new domain but it gives me this error:
403,0: <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>...

I tried changing name and TLD but nothing changed.
Maybe it has something to do with the new captcha?

**Comment by dotunwrap** [comment] 2024-06-04 12:47
Duplicate of #149. Known issue. Cloudflare is blocking traffic right now. It's being worked around now by @cl0wnZwormz as they are working with Cloudflare.

**Closed** 2024-06-04 12:56 UTC
Labels: bug
