### ISSUE TITLE
Failed due to ratelimit. Register

### ISSUE THREAD

**Issue by lucas11222** [face-hh/webx#31] opened 2024-05-31 16:52 UTC
i only put one time bad and now i cant upload my page

**Comment by Smartlinuxcoder** [comment] 2024-05-31 16:53
You just have to wait 1 hour

**Comment by Siomek101** [comment] 2024-05-31 16:56
Duplicate of #27

**Comment by face-hh** [comment] 2024-05-31 16:57
Duplicate of #27

**Closed by face-hh** 2024-05-31 16:57 UTC
