### ISSUE TITLE
Napture is unusable

### ISSUE THREAD

**Issue by Adrik-LOL** [face-hh/webx#116] opened 2024-06-02 08:48 UTC
it won't let me go to a single website or even dingle without freezing, crashing, un crashing, freezing again and finally letting me all in the span of 1:30 minutes is you are lucky, if you aren't you will suffer the program's crashing

![image](https://github.com/face-hh/webx/assets/45169953/d559b8eb-82b2-43fb-a987-c736ff824033)

**Comment by CharlesGameDev** [comment] 2024-06-02 08:56
nuh uh

**Comment by face-hh** [comment] 2024-06-02 09:39
Duplicate of #68

**Closed by face-hh** 2024-06-02 09:39 UTC
