### ISSUE TITLE
BUG: Portable Windows version not loading properly on Windows 11

### ISSUE THREAD

**Issue by lolzaws** [face-hh/webx#206] opened 2024-07-08 03:05 UTC
I installed Bussin_Napture-portable.paf.exe and ran it, you can see it below: ![image](https://github.com/face-hh/webx/assets/110387605/9f110168-b354-4c7d-af09-8782473e3bc8)

So it shows a text bar(assumed, because when I hover my mouse over, it triggers mouse entry text icon) , I think it may be the search box, anyway it stay like that and doesn't "load"(invisible wall, so loads technically, but doesn't show up) the rest of the UI. 

My laptop is running Windows 11 Pro 22H2 10.0.22621 64bit

**Comment by KubaPro010** [comment] 2024-07-08 12:55
Duplicate of #50

**Comment by lolzaws** [comment] 2024-07-08 19:59
> Duplicate of #50

Oh, thank you!

**Closed as completed** 2024-07-08 20:00 UTC
Labels: bug
