### ISSUE TITLE
Doesn't load images on Windows

### ISSUE THREAD

**Issue by hi101000** [face-hh/webx#105] opened 2024-06-01 23:58 UTC
The pre-built version for Windows can't load images, making the captcha impossible to fill out (among other things) when registering a website domain.

**Comment by Not-Alaksa-Airlines** [comment] 2024-06-02 00:00
This is already known of and being handled.

**Comment by face-hh** [comment] 2024-06-02 09:37
Duplicate of #34

**Closed by face-hh** 2024-06-02 09:37 UTC
