### ISSUE TITLE
Feature request: Can we have mutiple dns servers to query from instead of just one?

### ISSUE THREAD

**Issue by craft-o-s-project** [face-hh/webx#90] opened 2024-06-01 18:17 UTC

**Comment by Sakura-sx** [comment] 2024-06-01 18:22
Yes, and there are some people working on that, the only problem is that there can only be one central server, all the others have to get the domains from the central one.

**Comment by face-hh** [comment] 2024-06-02 09:34
Duplicate of #69

**Closed by face-hh** 2024-06-02 09:34 UTC
