### ISSUE TITLE
WINDOWS DON't work

### ISSUE THREAD

**Issue by NidroidX** [face-hh/webx#47] opened 2024-05-31 19:11 UTC
idk windows version not working. 
Almost it runs but idk seems something is missing cause not showing image and search and the home is empty.
IDK someone can help?
![webx](https://github.com/face-hh/webx/assets/67051882/e130d889-f016-44c1-8f2d-9ede3c86e8a8)

**Comment by face-hh** [comment] 2024-05-31 20:36
Duplicate of #34

**Closed by face-hh** 2024-05-31 20:36 UTC
