### ISSUE TITLE
Suggestion: fix images in windows prebuilt

### ISSUE THREAD

**Issue by virtualinmamity** [face-hh/webx#91] opened 2024-06-01 19:24 UTC

**Comment by Not-Alaksa-Airlines** [comment] 2024-06-01 22:11
I mean, yeah I hope that's already being done, but it is decently important so I hope it's close to the top of the to-do list.

**Comment by face-hh** [comment] 2024-06-02 09:38
Duplicate of #34

**Closed by face-hh** 2024-06-02 09:38 UTC
